// Writes src/main.e for `e.gfx.image.phash256`. Run from this directory:
//   node generate.mjs [path to mtg.studio.web]
// The eight real-art vectors are mtg.studio's Dart-emitted parity fixtures
// (tests/fixtures/scan-phash/vectors.json): each 64x64 grayscale is rebuilt as an Rgba8
// image whose pixels gray to exactly those bytes, so the resize is the identity and the
// hash must equal the Dart one. The synthetic images are LCG noise the fixture recomputes,
// hashed here by mtg.studio's JS port (js/domain/scan-phash.js), which is itself pinned
// bit-for-bit to the same Dart.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const root = process.argv[2] ?? 'D:/repos/mtg.studio.web';
const { pHash256, hashToHex, grayscaleValue } = await import(pathToFileURL(`${root}/js/domain/scan-phash.js`).href);
const fixtures = JSON.parse(readFileSync(`${root}/tests/fixtures/scan-phash/vectors.json`, 'utf8'));

// One RGB triple per gray byte whose Rec. 601 luma truncates back to that byte: (v, v, v)
// fails for 65 of the 256.
const triples = [];
for (let v = 0; v < 256; v++) {
    let found = null;
    for (let d = 0; d < 4 && !found; d++) {
        for (const [r, g, b] of [[v, v, v + d], [v, v + d, v], [v + d, v, v]]) {
            if (r < 256 && g < 256 && b < 256 && grayscaleValue(r, g, b) === v) { found = [r, g, b]; break; }
        }
    }
    if (!found) throw new Error(`no triple for ${v}`);
    triples.push(...found);
}
const hex = (a) => Buffer.from(a).toString('hex');

// The fixture's LCG: s = s * 1664525 + 1013904223 (mod 2^32), byte = s >> 24.
function noise(n, seed) {
    const out = new Uint8Array(n);
    let s = seed >>> 0;
    for (let i = 0; i < n; i++) {
        s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
        out[i] = s >>> 24;
    }
    return out;
}
// [name, width, height, format, bytes per pixel, stride, seed]
const synthetic = [
    ['Rgba8 137x191, shrunk by a non-integer ratio', 137, 191, 'Rgba8', 4, 548, 1],
    ['Bgra8 50x37 with a padded stride, enlarged', 50, 37, 'Bgra8', 4, 212, 2],
    ['R8 312x445, the old-frame card size', 312, 445, 'R8', 1, 312, 3],
    ['Rgba8 3x2, enlarged from almost nothing', 3, 2, 'Rgba8', 4, 12, 4],
];
const syntheticHashes = synthetic.map(([, w, h, format, bpp, stride, seed]) => {
    const raw = noise(stride * h, seed);
    const rgba = new Uint8Array(w * h * 4);
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
        const at = y * stride + x * bpp, o = (y * w + x) * 4;
        const [r, g, b] = format === 'R8' ? [raw[at], raw[at], raw[at]]
            : format === 'Bgra8' ? [raw[at + 2], raw[at + 1], raw[at]] : [raw[at], raw[at + 1], raw[at + 2]];
        rgba.set([r, g, b, 255], o);
    }
    return hashToHex(pHash256(rgba, w, h));
});

const lines = [
    '// `e.gfx.image.phash256` against mtg.studio\'s card-scan hash: eight real card arts from',
    '// its Dart-emitted parity vectors, each 64x64 grayscale rebuilt as Rgba8 pixels that gray',
    '// to exactly those bytes, and four LCG-noise images in every 8-bit format, with a padded',
    '// stride, enlarged and shrunk, hashed by its JS port. Generated by generate.mjs',
    '// beside this file. Every check has its own exit code.',
    'use e.bytes',
    'use e.gfx.image',
    'use e.mem',
    'use e.os',
    '',
    'fn same(hash: [32]u8, expected: str) -> bool {',
    '    var want: [32]u8 = zero',
    '    let (decoded, e) = bytes.hex_decode(want[..], expected)',
    '    if e != ok || decoded.len != 32usize { ret false }',
    '    var i = 0usize',
    '    while i < 32usize {',
    '        if hash[i] != want[i] { ret false }',
    '        i += 1usize',
    '    }',
    '    ret true',
    '}',
    '',
    '// A 64x64 grayscale as Rgba8 pixels, each byte through its triple.',
    'fn real(rgba: []u8, triples: []const u8, gray: str, expected: str, code: i32) {',
    '    var raw: [4096]u8 = zero',
    '    let (decoded, e) = bytes.hex_decode(raw[..], gray)',
    '    if e != ok || decoded.len != 4096usize { os.exit(code) }',
    '    var i = 0usize',
    '    while i < 4096usize {',
    '        let t = usize(raw[i]) * 3usize',
    '        rgba[i * 4usize] = triples[t]',
    '        rgba[i * 4usize + 1usize] = triples[t + 1usize]',
    '        rgba[i * 4usize + 2usize] = triples[t + 2usize]',
    '        rgba[i * 4usize + 3usize] = 255u8',
    '        i += 1usize',
    '    }',
    '    let (img, img_error) = image.make_const(rgba[..16384usize], 64u32, 64u32, 256usize, .Rgba8, .Opaque)',
    '    if img_error != ok { os.exit(code) }',
    '    let (hash, hash_error) = image.phash256(img)',
    '    if hash_error != ok || !same(hash, expected) { os.exit(code + 1i32) }',
    '}',
    '',
    'fn synthetic(a: *mem.Arena, width: u32, height: u32, stride: usize, format: image.Format, seed: u32, expected: str, code: i32) {',
    '    let (raw, alloc_error) = mem.alloc[u8](a, stride * usize(height))',
    '    if alloc_error != ok { os.exit(code) }',
    '    var s = seed',
    '    var i = 0usize',
    '    while i < raw.len {',
    '        s = s *% 1664525u32 +% 1013904223u32',
    '        raw[i] = u8(s >> 24u32)',
    '        i += 1usize',
    '    }',
    '    let (img, img_error) = image.make_const(raw, width, height, stride, format, .Opaque)',
    '    if img_error != ok { os.exit(code) }',
    '    let (hash, hash_error) = image.phash256(img)',
    '    if hash_error != ok || !same(hash, expected) { os.exit(code + 1i32) }',
    '}',
    '',
    'fn main(a: *mem.Arena, args: []str) -> err {',
    '    var triples: [768]u8 = zero',
    `    let (decoded, e) = bytes.hex_decode(triples[..], "${hex(triples)}")`,
    '    if e != ok || decoded.len != 768usize { os.exit(1i32) }',
    '    var rgba: [16384]u8 = zero',
];
fixtures.vectors.forEach((v, i) => {
    lines.push(`    // ${v.name}, ${v.srcWidth}x${v.srcHeight}`);
    lines.push(`    real(rgba[..], triples[..], "${hex(v.gray64)}", "${v.hashHex}", ${10 + 2 * i}i32)`);
});
synthetic.forEach(([name, w, h, format, , stride, seed], i) => {
    lines.push(`    // ${name}`);
    lines.push(`    synthetic(a, ${w}u32, ${h}u32, ${stride}usize, .${format}, ${seed}u32, "${syntheticHashes[i]}", ${40 + 2 * i}i32)`);
});
lines.push(
    '    // One pixel hashes; a flat image\'s bits are rounding noise (D1570), so no expectation.',
    '    var one: [4]u8 = zero',
    '    let (px, px_error) = image.make_const(one[..], 1u32, 1u32, 4usize, .Rgba8, .Opaque)',
    '    if px_error != ok { os.exit(58i32) }',
    '    let (_, one_error) = image.phash256(px)',
    '    if one_error != ok { os.exit(59i32) }',
    '    // A half-float view and an empty one have no hash.',
    '    var half: [8]u8 = zero',
    '    let (hf, hf_error) = image.make_const(half[..], 1u32, 1u32, 8usize, .Rgba16Float, .Opaque)',
    '    if hf_error != ok { os.exit(60i32) }',
    '    let (_, half_error) = image.phash256(hf)',
    '    if half_error != image.Invalid { os.exit(61i32) }',
    '    let (empty, empty_error) = image.make_const(half[..0usize], 0u32, 0u32, 0usize, .Rgba8, .Opaque)',
    '    if empty_error != ok { os.exit(62i32) }',
    '    let (_, none_error) = image.phash256(empty)',
    '    if none_error != image.Invalid { os.exit(63i32) }',
    '    ret ok',
    '}',
);
writeFileSync('src/main.e', lines.join('\n') + '\n');
