// `e.text.normalize` (D301): the four forms over composition, reordering, exclusions,
// Hangul and compatibility mappings, and `is_normalized` agreeing with them. Every
// expectation was generated by reference.py beside this file from Python's unicodedata.
// Every check exits with its own number; 0 is every check passed.
use e.os
use e.mem
use e.str
use e.text.normalize as norm

fn gives(a: *mem.Arena, s: str, form: norm.Form, want: str) -> bool {
    let (out, out_error) = norm.normalize(a, s, form)
    if out_error != ok { ret false }
    ret str.eq(out, want)
}

fn holds(s: str, form: norm.Form, want: bool) -> bool {
    let (answer, answer_error) = norm.is_normalized(s, form)
    if answer_error != ok { ret false }
    ret answer == want
}

fn main(a: *mem.Arena, args: []str) -> err {
    // --- the one-scalar / two-scalar pair in both directions ---------------------------
    if !gives(a, "\xc3\xa9", .Nfd, "e\xcc\x81") { os.exit(1) }
    if !gives(a, "\xc3\xa9", .Nfc, "\xc3\xa9") { os.exit(2) }
    if !gives(a, "e\xcc\x81", .Nfc, "\xc3\xa9") { os.exit(3) }
    if !gives(a, "e\xcc\x81", .Nfd, "e\xcc\x81") { os.exit(4) }
    if !gives(a, "\xc3\xa9", .Nfkd, "e\xcc\x81") { os.exit(5) }
    if !gives(a, "e\xcc\x81", .Nfkc, "\xc3\xa9") { os.exit(6) }

    // --- canonical ordering: cedilla (202) sorts before acute (230) --------------------
    if !gives(a, "a\xcc\x81\xcc\xa7", .Nfd, "a\xcc\xa7\xcc\x81") { os.exit(7) }
    if !gives(a, "a\xcc\xa7\xcc\x81", .Nfd, "a\xcc\xa7\xcc\x81") { os.exit(8) }
    // Composition reaches past the cedilla to the acute, because 202 < 230 does not block.
    if !gives(a, "a\xcc\x81\xcc\xa7", .Nfc, "\xc3\xa1\xcc\xa7") { os.exit(9) }
    if !gives(a, "a\xcc\xa7\xcc\x81", .Nfc, "\xc3\xa1\xcc\xa7") { os.exit(10) }
    // A string that starts with a mark reorders and composes nothing.
    if !gives(a, "\xcc\x81\xcc\xa7", .Nfd, "\xcc\xa7\xcc\x81") { os.exit(11) }
    if !gives(a, "\xcc\x81\xcc\xa7", .Nfc, "\xcc\xa7\xcc\x81") { os.exit(12) }
    // Blocked: a second acute behind the first has an equal class and stays.
    if !gives(a, "e\xcc\x81\xcc\x81", .Nfc, "\xc3\xa9\xcc\x81") { os.exit(13) }

    // --- Hangul, arithmetic both ways ------------------------------------------------------
    if !gives(a, "\xed\x95\x9c\xea\xb8\x80", .Nfd, "\xe1\x84\x92\xe1\x85\xa1\xe1\x86\xab\xe1\x84\x80\xe1\x85\xb3\xe1\x86\xaf") { os.exit(14) }
    if !gives(a, "\xe1\x84\x92\xe1\x85\xa1\xe1\x86\xab\xe1\x84\x80\xe1\x85\xb3\xe1\x86\xaf", .Nfc, "\xed\x95\x9c\xea\xb8\x80") { os.exit(15) }
    if !gives(a, "\xe1\x84\x80\xe1\x85\xa1\xe1\x86\xa8", .Nfc, "\xea\xb0\x81") { os.exit(16) }
    // An LV syllable followed by a T jamo composes to LVT.
    if !gives(a, "\xea\xb0\x80\xe1\x86\xa8", .Nfc, "\xea\xb0\x81") { os.exit(17) }
    if !gives(a, "\xea\xb0\x80\xe1\x86\xa8", .Nfd, "\xe1\x84\x80\xe1\x85\xa1\xe1\x86\xa8") { os.exit(18) }

    // --- compatibility mappings are invisible to the canonical forms -----------------------
    if !gives(a, "\xef\xac\x81", .Nfd, "\xef\xac\x81") { os.exit(19) }
    if !gives(a, "\xef\xac\x81", .Nfkd, "fi") { os.exit(20) }
    if !gives(a, "\xef\xac\x81", .Nfkc, "fi") { os.exit(21) }
    if !gives(a, "\xe2\x91\xa0", .Nfkc, "1") { os.exit(22) }
    if !gives(a, "\xe2\x91\xa0", .Nfc, "\xe2\x91\xa0") { os.exit(23) }
    if !gives(a, "\xef\xbc\xa1", .Nfkd, "A") { os.exit(24) }
    // The widest mapping: U+FDFA to eighteen scalars.
    if !gives(a, "\xef\xb7\xba", .Nfkd, "\xd8\xb5\xd9\x84\xd9\x89 \xd8\xa7\xd9\x84\xd9\x84\xd9\x87 \xd8\xb9\xd9\x84\xd9\x8a\xd9\x87 \xd9\x88\xd8\xb3\xd9\x84\xd9\x85") { os.exit(25) }
    if !gives(a, "\xef\xb7\xba", .Nfd, "\xef\xb7\xba") { os.exit(26) }

    // --- exclusions and singletons: decomposed under every form ----------------------------
    if !gives(a, "\xe0\xa5\x98", .Nfc, "\xe0\xa4\x95\xe0\xa4\xbc") { os.exit(27) }
    if !gives(a, "\xe0\xa5\x98", .Nfd, "\xe0\xa4\x95\xe0\xa4\xbc") { os.exit(28) }
    if !gives(a, "\xe2\x84\xa6", .Nfc, "\xce\xa9") { os.exit(29) }
    if !gives(a, "\xe2\x84\xa6", .Nfd, "\xce\xa9") { os.exit(30) }
    // U+0F73 is a starter whose decomposition is two non-starters, and it is excluded.
    if !gives(a, "\xe0\xbd\xb3", .Nfd, "\xe0\xbd\xb1\xe0\xbd\xb2") { os.exit(31) }
    if !gives(a, "\xe0\xbd\xb3", .Nfc, "\xe0\xbd\xb1\xe0\xbd\xb2") { os.exit(32) }

    // --- recursion: UnicodeData is single-level, the forms are not ---------------------------
    if !gives(a, "\xe1\xb9\xa9", .Nfd, "s\xcc\xa3\xcc\x87") { os.exit(33) }
    if !gives(a, "s\xcc\xa3\xcc\x87", .Nfc, "\xe1\xb9\xa9") { os.exit(34) }
    if !gives(a, "\xe1\xbe\x82", .Nfd, "\xce\xb1\xcc\x93\xcc\x80\xcd\x85") { os.exit(35) }
    if !gives(a, "\xce\xb1\xcc\x93\xcc\x80\xcd\x85", .Nfc, "\xe1\xbe\x82") { os.exit(36) }

    // --- mixed text, empty, ASCII, malformed --------------------------------------------
    if !gives(a, "caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c", .Nfd, "cafe\xcc\x81 \xef\xac\x81n \xe1\x84\x92\xe1\x85\xa1\xe1\x86\xab") { os.exit(37) }
    if !gives(a, "caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c", .Nfkc, "caf\xc3\xa9 fin \xed\x95\x9c") { os.exit(38) }
    if !gives(a, "caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c", .Nfkd, "cafe\xcc\x81 fin \xe1\x84\x92\xe1\x85\xa1\xe1\x86\xab") { os.exit(39) }
    if !gives(a, "caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c", .Nfc, "caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c") { os.exit(40) }
    if !gives(a, "", .Nfc, "") { os.exit(41) }
    if !gives(a, "plain ascii", .Nfkd, "plain ascii") { os.exit(42) }
    let (bad, bad_error) = norm.normalize(a, "ab\xffcd", .Nfc)
    if bad_error != norm.Invalid { os.exit(43) }
    // Idempotent: normalizing a result changes nothing.
    let (once, once_error) = norm.normalize(a, "a\xcc\x81\xcc\xa7\xea\xb0\x80\xe1\x86\xa8\xef\xac\x81", .Nfkc)
    if once_error != ok { os.exit(44) }
    let (twice, twice_error) = norm.normalize(a, once, .Nfkc)
    if twice_error != ok || !str.eq(once, twice) { os.exit(45) }

    // --- is_normalized agrees with normalize ----------------------------------------------
    if !holds("\xc3\xa9", .Nfc, true) { os.exit(46) }
    if !holds("\xc3\xa9", .Nfd, false) { os.exit(47) }
    if !holds("e\xcc\x81", .Nfc, false) { os.exit(48) }
    if !holds("e\xcc\x81", .Nfd, true) { os.exit(49) }
    if !holds("\xef\xac\x81", .Nfc, true) { os.exit(50) }
    if !holds("\xef\xac\x81", .Nfkc, false) { os.exit(51) }
    if !holds("a\xcc\x81\xcc\xa7", .Nfd, false) { os.exit(52) }
    if !holds("a\xcc\xa7\xcc\x81", .Nfd, true) { os.exit(53) }
    if !holds("\xed\x95\x9c\xea\xb8\x80", .Nfc, true) { os.exit(54) }
    if !holds("\xed\x95\x9c\xea\xb8\x80", .Nfd, false) { os.exit(55) }
    // The cut rule must not split an L jamo from its V, or an LV syllable from its T.
    if !holds("\xe1\x84\x80\xe1\x85\xa1\xe1\x86\xa8", .Nfc, false) { os.exit(56) }
    if !holds("\xea\xb0\x80\xe1\x86\xa8", .Nfc, false) { os.exit(57) }
    // Nor a starter from a starter second: Bengali KA + AA composes to U+09CB.
    if !holds("\xe0\xa7\x87\xe0\xa6\xbe", .Nfc, false) { os.exit(58) }
    if !gives(a, "\xe0\xa7\x87\xe0\xa6\xbe", .Nfc, "\xe0\xa7\x8b") { os.exit(59) }
    if !holds("plain ascii", .Nfkd, true) { os.exit(60) }
    if !holds("", .Nfc, true) { os.exit(61) }
    if !holds("caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c", .Nfc, true) { os.exit(62) }
    if !holds("caf\xc3\xa9 \xef\xac\x81n \xed\x95\x9c", .Nfkc, false) { os.exit(63) }
    if !holds("\xe0\xa5\x98", .Nfc, false) { os.exit(64) }
    if !holds("\xe2\x84\xa6", .Nfc, false) { os.exit(65) }
    let (malformed, malformed_error) = norm.is_normalized("ab\xffcd", .Nfc)
    if malformed_error != norm.Invalid { os.exit(66) }
    ret ok
}
