// Importer type maps (L044), generated by scripts/typemaps_gen.mjs from Appdor's src/importers/{monday,airtable,quickbase}.js:
// the source tool's field types and view types as Appdor's. A field type the map does not list is the importer's own
// decision (text); a view type it does not list is a `grid`, because a grid shows every row.
//
// ponytail: Appdor's maps are plain objects, so a source type named like an Object.prototype member
// (`constructor`, `toString`) reads an inherited function there; these tables answer only the listed names.

use e.str

// A monday column type as an Appdor field type; false for a type the map does not list (the importer falls back to text).
fn monday_type(key: str) -> (str, bool) {
    if str.eq(key, "text") { ret ("text", true) }
    if str.eq(key, "long_text") { ret ("long-text", true) }
    if str.eq(key, "numbers") { ret ("number", true) }
    if str.eq(key, "numeric") { ret ("number", true) }
    if str.eq(key, "status") { ret ("select", true) }
    if str.eq(key, "color") { ret ("select", true) }
    if str.eq(key, "dropdown") { ret ("multiselect", true) }
    if str.eq(key, "tags") { ret ("multiselect", true) }
    if str.eq(key, "date") { ret ("date", true) }
    if str.eq(key, "timeline") { ret ("date", true) }
    if str.eq(key, "hour") { ret ("text", true) }
    if str.eq(key, "week") { ret ("text", true) }
    if str.eq(key, "world_clock") { ret ("text", true) }
    if str.eq(key, "people") { ret ("text", true) }
    if str.eq(key, "person") { ret ("text", true) }
    if str.eq(key, "email") { ret ("email", true) }
    if str.eq(key, "phone") { ret ("phone", true) }
    if str.eq(key, "link") { ret ("url", true) }
    if str.eq(key, "checkbox") { ret ("checkbox", true) }
    if str.eq(key, "boolean") { ret ("checkbox", true) }
    if str.eq(key, "rating") { ret ("rating", true) }
    if str.eq(key, "vote") { ret ("number", true) }
    if str.eq(key, "country") { ret ("text", true) }
    if str.eq(key, "location") { ret ("text", true) }
    if str.eq(key, "formula") { ret ("formula", true) }
    if str.eq(key, "board_relation") { ret ("link", true) }
    if str.eq(key, "dependency") { ret ("link", true) }
    if str.eq(key, "mirror") { ret ("text", true) }
    if str.eq(key, "file") { ret ("attachment", true) }
    if str.eq(key, "item_id") { ret ("number", true) }
    if str.eq(key, "creation_log") { ret ("datetime", true) }
    if str.eq(key, "last_updated") { ret ("datetime", true) }
    if str.eq(key, "auto_number") { ret ("number", true) }
    ret ("", false)
}

// An Airtable field type as an Appdor field type; false for a type the map does not list (the importer falls back to text).
fn airtable_type(key: str) -> (str, bool) {
    if str.eq(key, "singleLineText") { ret ("text", true) }
    if str.eq(key, "multilineText") { ret ("long-text", true) }
    if str.eq(key, "richText") { ret ("long-text", true) }
    if str.eq(key, "number") { ret ("number", true) }
    if str.eq(key, "currency") { ret ("currency", true) }
    if str.eq(key, "percent") { ret ("percent", true) }
    if str.eq(key, "duration") { ret ("duration", true) }
    if str.eq(key, "autoNumber") { ret ("number", true) }
    if str.eq(key, "singleSelect") { ret ("select", true) }
    if str.eq(key, "multipleSelects") { ret ("multiselect", true) }
    if str.eq(key, "date") { ret ("date", true) }
    if str.eq(key, "dateTime") { ret ("datetime", true) }
    if str.eq(key, "createdTime") { ret ("datetime", true) }
    if str.eq(key, "lastModifiedTime") { ret ("datetime", true) }
    if str.eq(key, "checkbox") { ret ("checkbox", true) }
    if str.eq(key, "email") { ret ("email", true) }
    if str.eq(key, "url") { ret ("url", true) }
    if str.eq(key, "phoneNumber") { ret ("phone", true) }
    if str.eq(key, "rating") { ret ("rating", true) }
    if str.eq(key, "formula") { ret ("formula", true) }
    if str.eq(key, "rollup") { ret ("rollup", true) }
    if str.eq(key, "count") { ret ("count", true) }
    if str.eq(key, "multipleLookupValues") { ret ("lookup", true) }
    if str.eq(key, "multipleRecordLinks") { ret ("link", true) }
    if str.eq(key, "multipleAttachments") { ret ("attachment", true) }
    if str.eq(key, "barcode") { ret ("barcode", true) }
    if str.eq(key, "singleCollaborator") { ret ("text", true) }
    if str.eq(key, "multipleCollaborators") { ret ("multiselect", true) }
    if str.eq(key, "createdBy") { ret ("text", true) }
    if str.eq(key, "lastModifiedBy") { ret ("text", true) }
    ret ("", false)
}

// A Quickbase field type as an Appdor field type; false for a type the map does not list.
fn quickbase_type(key: str) -> (str, bool) {
    if str.eq(key, "text") { ret ("text", true) }
    if str.eq(key, "text-multi-line") { ret ("long-text", true) }
    if str.eq(key, "text-multiple-choice") { ret ("select", true) }
    if str.eq(key, "rich-text") { ret ("long-text", true) }
    if str.eq(key, "numeric") { ret ("number", true) }
    if str.eq(key, "currency") { ret ("currency", true) }
    if str.eq(key, "percent") { ret ("percent", true) }
    if str.eq(key, "rating") { ret ("rating", true) }
    if str.eq(key, "checkbox") { ret ("checkbox", true) }
    if str.eq(key, "date") { ret ("date", true) }
    if str.eq(key, "timestamp") { ret ("datetime", true) }
    if str.eq(key, "timeofday") { ret ("text", true) }
    if str.eq(key, "duration") { ret ("duration", true) }
    if str.eq(key, "email") { ret ("email", true) }
    if str.eq(key, "url") { ret ("url", true) }
    if str.eq(key, "phone") { ret ("phone", true) }
    if str.eq(key, "address") { ret ("text", true) }
    if str.eq(key, "user") { ret ("user", true) }
    if str.eq(key, "multiuser") { ret ("user", true) }
    if str.eq(key, "file") { ret ("attachment", true) }
    if str.eq(key, "multitext") { ret ("multiselect", true) }
    if str.eq(key, "recordid") { ret ("number", true) }
    if str.eq(key, "dblink") { ret ("url", true) }
    if str.eq(key, "icalendarbutton") { ret ("text", true) }
    if str.eq(key, "vcardbutton") { ret ("text", true) }
    if str.eq(key, "predecessor") { ret ("dependency", true) }
    if str.eq(key, "work-date") { ret ("date", true) }
    if str.eq(key, "reference") { ret ("link", true) }
    if str.eq(key, "foreignkey") { ret ("link", true) }
    ret ("", false)
}

// An Airtable view type as an Appdor view type; anything unlisted is a `grid`, which shows every row.
fn airtable_view_type(key: str) -> str {
    if str.eq(key, "grid") { ret "grid" }
    if str.eq(key, "kanban") { ret "kanban" }
    if str.eq(key, "calendar") { ret "calendar" }
    if str.eq(key, "gallery") { ret "gallery" }
    if str.eq(key, "form") { ret "form" }
    if str.eq(key, "timeline") { ret "timeline" }
    if str.eq(key, "gantt") { ret "timeline" }
    if str.eq(key, "block") { ret "grid" }
    ret "grid"
}

// A monday view type as an Appdor view type; anything unlisted is a `grid`, which shows every row.
fn monday_view_type(key: str) -> str {
    if str.eq(key, "table") { ret "grid" }
    if str.eq(key, "kanban") { ret "kanban" }
    if str.eq(key, "calendar") { ret "calendar" }
    if str.eq(key, "timeline") { ret "timeline" }
    if str.eq(key, "gantt") { ret "timeline" }
    if str.eq(key, "form") { ret "form" }
    if str.eq(key, "chart") { ret "chart" }
    ret "grid"
}
