# Writes src/main.e: one function of 3000 checks (D302). Under the two-tier NIR pools it
# overran the small tier at check 2730, and once past lowering it overran codegen's flat
# 8192-entry per-function block table. Both are program-sized now; this pins that a wide
# function compiles and computes the right sum. Run from this directory.
N = 3000
lines = [
    "// One function of %d checks (D302): wider than the small NIR tier and than codegen's" % N,
    "// old per-function block table. Generated by generate.py beside this file; the sum is",
    "// checked at the end so the body cannot be skipped. Exit 0 is every check passed.",
    "use e.os",
    "use e.mem",
    "",
    "fn main(a: *mem.Arena, args: []str) -> err {",
    "    var acc = 0i64",
]
for i in range(1, N + 1):
    lines.append("    acc = acc + %di64" % i)
    lines.append("    if acc < 0i64 { os.exit(%d) }" % (i % 250 + 1))
lines += ["    if acc != %di64 { os.exit(255) }" % (N * (N + 1) // 2), "    ret ok", "}"]
open('src/main.e', 'w', newline='\n').write("\n".join(lines) + "\n")
