"""Render docs/llm-neper-card.md from the grammar and the registries (D374, H28).

    python scripts/render_card.py            # write docs/llm-neper-card.md
    python scripts/render_card.py --check    # exit 1 when the committed card is not the render

The card's syntax sections are the grammar's own productions, copied from
docs/grammar.ebnf; its keyword list is every alphabetic terminal of that grammar; its
diagnostic families are docs/diagnostics.md's registry; its versions are the ones the
compiler writes in every stream header (src/main.e). The prose around them is
docs/llm-neper-card.src.md. The rendered card carries the grammar revision, the
language and tool versions and a content hash, so a card and the grammar cannot
drift: the suites run --check.
"""
import hashlib, os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def read(*parts):
    with open(os.path.join(root, *parts), encoding='utf-8') as f:
        return f.read()

grammar = read('docs', 'grammar.ebnf')
revision = re.search(r'revision (\d+)', grammar.splitlines()[0]).group(1)
main_source = read('src', 'main.e')
tool_version = re.search(r'"tool_version\\":\\"([^\\]+)\\"', main_source).group(1)
language_version = re.search(r'"language_version\\":\\"([^\\]+)\\"', main_source).group(1)

# A production and its continuation lines, verbatim.
productions = {}
current = None
for line in grammar.splitlines():
    m = re.match(r'^([a-z_]+)\s*=', line)
    if m:
        current = m.group(1)
        productions[current] = [line]
    elif current and line.startswith(' ') and line.strip():
        productions[current].append(line)
    else:
        current = None

def block(names):
    out = []
    for name in names:
        out.extend(productions[name])
    return '\n'.join(out)

DECLARATIONS = ['top_decl', 'use_decl', 'attribute', 'type_decl', 'const_decl', 'var_decl', 'error_decl', 'fn_decl', 'extern_decl', 'signature', 'parameter', 'comptime_params', 'comptime_param', 'comptime_kind']
TYPES = ['type_rhs', 'resource_prefix', 'struct_type', 'union_type', 'enum_type', 'union_enum_type', 'field_decl', 'enum_member', 'union_member', 'type_expr', 'pointer_type', 'slice_type', 'array_type', 'function_type', 'named_type']
STATEMENTS = ['statement', 'binding_stmt', 'assignment_stmt', 'try_stmt', 'defer_stmt', 'if_stmt', 'while_stmt', 'for_stmt']
EXPRESSIONS = ['expression', 'postfix', 'postfix_part', 'primary', 'literal']
for name in DECLARATIONS + TYPES + STATEMENTS + EXPRESSIONS:
    if name not in productions:
        sys.exit('render_card: grammar.ebnf has no production %s' % name)

# Keywords: the alphabetic terminals of the productions, not of the notation comments,
# and not `_`, which is a binding, nor lexer fragments of a number.
production_text = '\n'.join(line for line in grammar.splitlines() if not line.startswith('#'))
keywords = sorted(k for k in set(re.findall(r'`([a-z][a-z_]+)`', production_text)) if len(k) > 1)

codes = re.findall(r'^\| `(E-([A-Z]+)-(\d{4}))` \| ([^|]+) \|', read('docs', 'diagnostics.md'), re.M)
families = {}
for code, family, number, meaning in codes:
    families.setdefault(family, []).append((code, meaning.strip()))
diagnostics = '\n'.join(
    '- `E-%s-*`: %d codes; `%s` is the catch-all' % (family, len(entries), entries[-1][0])
    for family, entries in sorted(families.items()))

template = read('docs', 'llm-neper-card.src.md')
body = template
for key, value in [
    ('{{revision}}', revision), ('{{language_version}}', language_version), ('{{tool_version}}', tool_version),
    ('{{keywords}}', ' '.join('`%s`' % k for k in keywords)),
    ('{{declarations}}', block(DECLARATIONS)), ('{{types}}', block(TYPES)),
    ('{{statements}}', block(STATEMENTS)), ('{{expressions}}', block(EXPRESSIONS)),
    ('{{diagnostics}}', diagnostics),
]:
    body = body.replace(key, value)
if '{{' in body:
    sys.exit('render_card: an unfilled placeholder: %s' % re.search(r'\{\{[^}]*\}\}', body).group(0))
digest = hashlib.sha256(body.encode('utf-8')).hexdigest()
card = ('<!-- generated by scripts/render_card.py from docs/grammar.ebnf revision %s, language %s, tool %s; content sha256 %s. Do not edit: edit docs/llm-neper-card.src.md and re-render. -->\n' % (revision, language_version, tool_version, digest)) + body

path = os.path.join(root, 'docs', 'llm-neper-card.md')
if '--check' in sys.argv:
    with open(path, encoding='utf-8') as f:
        committed = f.read()
    if committed != card:
        print('render_card: docs/llm-neper-card.md is not the render of grammar.ebnf revision %s; run python scripts/render_card.py' % revision)
        sys.exit(1)
    print('card current: grammar revision %s, sha256 %s' % (revision, digest[:12]))
else:
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(card)
    print('wrote docs/llm-neper-card.md (grammar revision %s, sha256 %s)' % (revision, digest[:12]))
