// Generates lib/x/migrate/typemaps.e (L044) from Appdor's own importer maps (src/importers/{monday,airtable,quickbase}.js):
// source field-type to Appdor field-type, and source view-type to Appdor view-type. Usage: node scripts/typemaps_gen.mjs
// APPDOR_DIR defaults to D:/repos/appdor.
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appdor = process.env.APPDOR_DIR || 'D:/repos/appdor';
const load = (f) => import(pathToFileURL(resolve(appdor, 'src/importers', f)).href);
const [monday, airtable, quickbase] = await Promise.all([load('monday.js'), load('airtable.js'), load('quickbase.js')]);
const maps = [
  ['monday_type', 'A monday column type as an Appdor field type; false for a type the map does not list (the importer falls back to text).', monday.MONDAY_TYPE_MAP],
  ['airtable_type', 'An Airtable field type as an Appdor field type; false for a type the map does not list (the importer falls back to text).', airtable.AIRTABLE_TYPE_MAP],
  ['quickbase_type', 'A Quickbase field type as an Appdor field type; false for a type the map does not list.', quickbase.QUICKBASE_TYPE_MAP],
  ['airtable_view_type', 'An Airtable view type as an Appdor view type; anything unlisted is a `grid`, which shows every row.', airtable.AIRTABLE_VIEW_TYPE_MAP],
  ['monday_view_type', 'A monday view type as an Appdor view type; anything unlisted is a `grid`, which shows every row.', monday.MONDAY_VIEW_TYPE_MAP],
];
let out = `// Importer type maps (L044), generated by scripts/typemaps_gen.mjs from Appdor's src/importers/{monday,airtable,quickbase}.js:
// the source tool's field types and view types as Appdor's. A field type the map does not list is the importer's own
// decision (text); a view type it does not list is a \`grid\`, because a grid shows every row.
//
// ponytail: Appdor's maps are plain objects, so a source type named like an Object.prototype member
// (\`constructor\`, \`toString\`) reads an inherited function there; these tables answer only the listed names.

`;
for (const [name, doc, map] of maps) {
  const view = name.endsWith('view_type');
  out += `// ${doc}\n`;
  if (view) {
    out += `fn ${name}(key: str) -> str {\n`;
    for (const [k, v] of Object.entries(map)) out += `    if str.eq(key, ${JSON.stringify(k)}) { ret ${JSON.stringify(v)} }\n`;
    out += `    ret "grid"\n}\n\n`;
  } else {
    out += `fn ${name}(key: str) -> (str, bool) {\n`;
    for (const [k, v] of Object.entries(map)) out += `    if str.eq(key, ${JSON.stringify(k)}) { ret (${JSON.stringify(v)}, true) }\n`;
    out += `    ret ("", false)\n}\n\n`;
  }
}
out = out.replace('// decision (text);', '// decision (text);').trimEnd() + '\n';
out = out.replace('\n\n// A monday column', '\n\nuse e.str\n\n// A monday column');
writeFileSync(resolve(here, '..', 'lib/x/migrate/typemaps.e'), out, 'utf8');
console.log(maps.map(([n, , m]) => `${n}: ${Object.keys(m).length}`).join(', '));
