// Frozen grammar revision 1 syntax-node registry.

type Kind = enum u8 {
    File,
    UseDecl,
    Attribute,
    TypeDecl,
    ConstDecl,
    VarDecl,
    ErrorDecl,
    FnDecl,
    ExternDecl,
    ComptimeParam,
    Parameter,
    ReturnSpec,
    StructType,
    UnionType,
    EnumType,
    UnionEnumType,
    FieldDecl,
    EnumMember,
    UnionMember,
    PointerType,
    SliceType,
    ArrayType,
    FunctionType,
    NamedType,
    Block,
    Binding,
    BindingStmt,
    AssignmentStmt,
    CallStmt,
    TryStmt,
    ReturnStmt,
    DeferStmt,
    NocheckStmt,
    SharedVarStmt,
    BreakStmt,
    ContinueStmt,
    IfStmt,
    WhileStmt,
    ForStmt,
    WhenStmt,
    SwitchStmt,
    SwitchArm,
    UnaryExpr,
    BinaryExpr,
    FieldExpr,
    BracketPostfix,
    CallExpr,
    NameExpr,
    MemberExpr,
    GroupExpr,
    AggregateLiteral,
    LiteralItem,
    LiteralExpr,
    ErrorNode,
}

type Node = struct {
    kind: Kind,
    token_start: usize,
    token_end: usize,
}
