const W = 1280
const H = 720
const BG = "#080a0f"
const PANEL = "#12151d"
const PANEL_2 = "#192131"
const TEXT = "#f1f3fb"
const MUTED = "#aeb6c9"
const BLUE = "#a8c2ff"
const BLUE_DARK = "#0758a5"
const GREEN = "#8ff0b0"
const COPPER = "#ffb08a"
const FONT = "Metropolis"
const MONO = "Montserrat"

const fade = { enter: { from: { opacity: 0 }, duration: 0.28, easing: "ease-out" } }

const heading = (number, eyebrow, headline, body) => (
  <frame x={72} y={48} width={1136} height={148} layout="none">
    <text x={0} y={0} width={90} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} color={BLUE}>{number}</text>
    <text x={90} y={0} width={1046} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} letterSpacing={1} color={BLUE}>{eyebrow}</text>
    <text x={0} y={34} width={1136} height={58} fontFamily={FONT} fontSize={43} fontWeight={600} color={TEXT}>{headline}</text>
    <text x={0} y={108} width={1136} height={24} fontFamily={FONT} fontSize={16} color={MUTED}>{body}</text>
  </frame>
)

const stat = (x, width, label, value, note, color = BLUE) => (
  <frame x={x} y={0} width={width} height={170} layout="none">
    <rect x={0} y={0} width={width} height={170} radius={18} fill={PANEL} />
    <rect x={0} y={0} width={8} height={170} radius={4} fill={color} />
    <text x={28} y={22} width={width - 50} height={20} fontFamily={MONO} fontSize={12} fontWeight={700} letterSpacing={1} color={MUTED}>{label}</text>
    <text x={28} y={58} width={width - 50} height={52} fontFamily={FONT} fontSize={38} fontWeight={600} color={TEXT}>{value}</text>
    <text x={28} y={122} width={width - 50} height={24} fontFamily={FONT} fontSize={14} color={MUTED}>{note}</text>
  </frame>
)

const pill = (x, width, label) => (
  <frame x={x} y={0} width={width} height={42} layout="none">
    <rect x={0} y={0} width={width} height={42} radius={21} fill="#34445f" />
    <text x={0} y={11} width={width} height={22} align="center" fontFamily={FONT} fontSize={13} fontWeight={700} color="#dbe6ff">{label}</text>
  </frame>
)

const featurePanel = (x, width, title, items, color = BLUE) => (
  <frame x={x} y={218} width={width} height={342} layout="none">
    <rect x={0} y={0} width={width} height={342} radius={18} fill={PANEL} />
    <rect x={0} y={0} width={8} height={342} radius={4} fill={color} />
    <text x={28} y={22} width={width - 48} height={26} fontFamily={MONO} fontSize={13} fontWeight={700} letterSpacing={1} color={color}>{title}</text>
    {items.map((item, i) => <text x={28} y={66 + i * 49} width={width - 48} height={38} fontFamily={FONT} fontSize={14} color={i % 2 ? MUTED : TEXT}>{item}</text>)}
  </frame>
)

export default async ({ project }) => {
  const p = await project({ dir: "neper-capabilities", size: `${W}x${H}`, fps: 30, background: BG })
  const forge = await p.add("forge.png")
  const logo = await p.add("neper-icon.png")

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      <rect x={-180} y={-240} width={780} height={780} radius={390} fill={{kind:"radial",stops:[{offset:0,color:"#143d73",opacity:.9},{offset:1,color:BG,opacity:0}]}} />
      <media file={logo} x={78} y={70} width={78} height={78} fit="contain" radius={20} />
      <text x={78} y={198} width={1120} height={82} fontFamily={FONT} fontSize={64} fontWeight={600} color={TEXT}>From prompt to proof.</text>
      <text x={82} y={304} width={1110} height={34} fontFamily={FONT} fontSize={27} color={MUTED}>The first general-purpose language optimized end to end</text>
      <text x={82} y={346} width={1110} height={34} fontFamily={FONT} fontSize={27} color={MUTED}>for software generated by language models.</text>
      <frame x={80} y={454} width={760} height={42} layout="none">{pill(0,166,"MIT open source")}{pill(182,224,"100% written in Neper")}{pill(422,252,"Windows / Linux / macOS")}</frame>
      <text x={82} y={548} width={1080} height={28} fontFamily={MONO} fontSize={15} fontWeight={700} color={BLUE}>NEPER  /  DETERMINISTIC BY DESIGN</text>
    </frame>,
    { at: 0, dur: 8.5, name: "From prompt to proof" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("01", "PROMPT > NATIVE", "One short program. One tiny binary.", "No VM, garbage collector, or LLVM runtime between source and native code.")}
      <frame x={72} y={220} width={720} height={356} layout="none">
        <rect x={0} y={0} width={720} height={356} radius={18} fill="#0d1017" /><rect x={0} y={0} width={720} height={48} radius={18} fill="#202634" /><rect x={0} y={30} width={720} height={18} fill="#202634" />
        <text x={24} y={14} width={670} height={22} fontFamily={MONO} fontSize={13} color={MUTED}>hello.e / neper</text>
      <text x={28} y={72} width={44} height={24} fontFamily={MONO} fontSize={19} fontWeight={700} color={BLUE}>use</text><text x={74} y={72} width={120} height={24} fontFamily={MONO} fontSize={19} color={TEXT}>e.io</text>
      <text x={28} y={112} width={34} height={24} fontFamily={MONO} fontSize={19} fontWeight={700} color={BLUE}>fn</text><text x={62} y={112} width={58} height={24} fontFamily={MONO} fontSize={19} fontWeight={700} color={BLUE}>main</text><text x={120} y={112} width={540} height={24} fontFamily={MONO} fontSize={19} color={TEXT}>{"(args: []str) -> err {"}</text>
      <text x={58} y={142} width={46} height={24} fontFamily={MONO} fontSize={19} fontWeight={700} color={BLUE}>try</text><text x={104} y={142} width={100} height={24} fontFamily={MONO} fontSize={19} color={TEXT}>io.print(</text><text x={204} y={142} width={166} height={24} fontFamily={MONO} fontSize={19} color={COPPER}>{'"Hello, Neper"'}</text><text x={370} y={142} width={24} height={24} fontFamily={MONO} fontSize={19} color={TEXT}>)</text>
      <text x={58} y={172} width={46} height={24} fontFamily={MONO} fontSize={19} fontWeight={700} color={BLUE}>ret</text><text x={104} y={172} width={40} height={24} fontFamily={MONO} fontSize={19} color={GREEN}>ok</text>
      <text x={28} y={202} width={660} height={24} fontFamily={MONO} fontSize={19} color={TEXT}>{"}"}</text>
      <text x={28} y={248} width={26} height={24} fontFamily={MONO} fontSize={19} color={GREEN}>$</text><text x={54} y={248} width={360} height={24} fontFamily={MONO} fontSize={19} color={TEXT}>neper run hello.e</text>
      <text x={28} y={286} width={660} height={24} fontFamily={MONO} fontSize={16} fontWeight={700} color={GREEN}>(32 msec, 3648 bytes)</text>
      <text x={28} y={316} width={660} height={24} fontFamily={MONO} fontSize={16} color={TEXT}>Hello, Neper</text>
      </frame>
      <frame x={824} y={220} width={384} height={356} layout="none">
        {stat(0,384,"BUILD","32 ms","prompt to running program",BLUE)}
        <frame x={0} y={186} width={384} height={170} layout="none"><rect x={0} y={0} width={384} height={170} radius={18} fill={PANEL} /><rect x={0} y={0} width={8} height={170} radius={4} fill={GREEN} /><text x={28} y={22} width={330} height={20} fontFamily={MONO} fontSize={12} fontWeight={700} color={MUTED}>EXECUTABLE</text><text x={28} y={58} width={330} height={52} fontFamily={FONT} fontSize={38} fontWeight={600} color={TEXT}>3,648 B</text><text x={28} y={122} width={330} height={24} fontFamily={FONT} fontSize={14} color={MUTED}>zero VM · native artifact</text></frame>
      </frame>
    </frame>,
    { at: 8.5, dur: 9, name: "Native build" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("02", "WHY SWITCH", "Less runtime. Less ambiguity. More proof.", "Go and TypeScript are excellent human-era tools. Neper removes the layers that make autonomous software harder to verify.")}
      <frame x={72} y={222} width={344} height={342} layout="none">
        <rect x={0} y={0} width={344} height={342} radius={18} fill={PANEL} /><text x={28} y={24} width={288} height={38} fontFamily={FONT} fontSize={28} fontWeight={600} color={TEXT}>Go</text>
        <text x={28} y={88} width={288} height={42} fontFamily={FONT} fontSize={16} color={MUTED}>Garbage-collected runtime</text><text x={28} y={145} width={288} height={42} fontFamily={FONT} fontSize={16} color={MUTED}>Tooling outside the language</text><text x={28} y={202} width={288} height={42} fontFamily={FONT} fontSize={16} color={MUTED}>No unified CPU + GPU module</text><text x={28} y={276} width={288} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} color={COPPER}>FAST, BUT RUNTIME-BOUND</text>
      </frame>
      <frame x={448} y={222} width={344} height={342} layout="none">
        <rect x={0} y={0} width={344} height={342} radius={18} fill={PANEL} /><text x={28} y={24} width={288} height={38} fontFamily={FONT} fontSize={28} fontWeight={600} color={TEXT}>TypeScript</text>
        <text x={28} y={88} width={288} height={42} fontFamily={FONT} fontSize={16} color={MUTED}>JavaScript plus transpilation</text><text x={28} y={145} width={288} height={42} fontFamily={FONT} fontSize={16} color={MUTED}>Package and build layers</text><text x={28} y={202} width={288} height={42} fontFamily={FONT} fontSize={16} color={MUTED}>Dynamic edges frustrate proof</text><text x={28} y={276} width={288} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} color={COPPER}>FLEXIBLE, BUT LAYERED</text>
      </frame>
      <frame x={824} y={222} width={384} height={342} layout="none">
        <rect x={0} y={0} width={384} height={342} radius={18} fill={BLUE_DARK} /><text x={28} y={24} width={328} height={38} fontFamily={FONT} fontSize={28} fontWeight={600} color="#ffffff">Neper</text>
        <text x={28} y={88} width={328} height={42} fontFamily={FONT} fontSize={16} color="#dbe6ff">Direct native toolchain</text><text x={28} y={145} width={328} height={42} fontFamily={FONT} fontSize={16} color="#dbe6ff">Compact explicit semantics</text><text x={28} y={202} width={328} height={42} fontFamily={FONT} fontSize={16} color="#dbe6ff">Proof-carrying workflow</text><text x={28} y={276} width={328} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} color={GREEN}>BUILT FOR AUTONOMOUS CODE</text>
      </frame>
    </frame>,
    { at: 17.5, dur: 9, name: "Why switch" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("03", "THE LLM CONTRACT", "Generate, understand, and edit without guessing.", "Fourteen model-facing guarantees reduce token cost, hidden choices, stale edits, and repair uncertainty.")}
      {featurePanel(72, 344, "GENERATE", ["Single-purpose keywords — fewer tokens", "No overloaded names — one resolution", "Search-stable declarations — cheap retrieval", "Canonical formatting — quieter diffs", "Measured token economics — cost enforced"], BLUE)}
      {featurePanel(448, 344, "UNDERSTAND", ["Bounded context — relevant facts only", "Compiler LLM cards — docs stay current", "Explicit semantics — no hidden behavior", "Lossless syntax — safe structural edits", "Stable JSON — no prose scraping"], COPPER)}
      {featurePanel(824, 384, "EDIT", ["Transactional edits — stale plans fail", "Semantic conflicts — meanings checked", "Machine repairs — fixes carry preconditions", "Generated source maps — edit real source"], GREEN)}
      <text x={74} y={594} width={1130} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} color={BLUE}>14 / 26 LLM-NATIVE FEATURES</text>
    </frame>,
    { at: 26.5, dur: 9, name: "LLM generation and editing" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("04", "THE VERIFICATION LOOP", "Build, diagnose, and prove objective completion.", "Twelve more guarantees bind the toolchain, diagnostics, tests, and final artifact into one deterministic stop state.")}
      {featurePanel(72, 344, "BUILD", ["Script-free packages — no install code", "Hermetic identity — ambient state excluded", "Declaration reuse — affected code only", "Direct toolchain — no VM or LLVM", "Optimization reasons — decisions exposed"], BLUE)}
      {featurePanel(448, 344, "VERIFY", ["Receipts — behavior to artifact", "Self-host fixed point — compiler checked", "Deterministic artifacts — results compare", "Unsafe inventory — every escape visible", "Built-in verification — evidence stops work"], GREEN)}
      {featurePanel(824, 384, "DIAGNOSE", ["Causal diagnostics — fix root causes", "Honest flaky tests — retries stay visible"], COPPER)}
      <text x={74} y={594} width={1130} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} color={GREEN}>26 / 26 LLM-NATIVE FEATURES  ·  FROM PROMPT TO PROOF</text>
    </frame>,
    { at: 35.5, dur: 9, name: "LLM build and verification" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("05", "ULTRA BY DESIGN", "One million lines. Under one second.", "Compile at thought speed, then keep only the functions, types, constants, and bytes the program can reach.")}
      <frame x={72} y={232} width={1136} height={170} layout="none">{stat(0,354,"THROUGHPUT","1M+ LOC","per second, per core",BLUE)}{stat(391,354,"REBUILD","< 1 sec","whole-project target",COPPER)}{stat(782,354,"DEAD WEIGHT","0 bytes","extreme elimination",GREEN)}</frame>
      <frame x={72} y={438} width={1136} height={118} layout="none"><rect x={0} y={0} width={1136} height={118} radius={18} fill={PANEL} /><text x={28} y={23} width={1050} height={22} fontFamily={MONO} fontSize={13} fontWeight={700} color={MUTED}>WHOLE-PROJECT BUILD</text><rect x={28} y={66} width={1080} height={12} radius={6} fill="#334159" /><rect x={28} y={66} width={1026} height={12} radius={6} fill={BLUE} animate={[{property:"scaleX",from:0,to:1,at:.4,duration:1.6,easing:"house"}]} /></frame>
      <text x={74} y={584} width={1130} height={24} fontFamily={MONO} fontSize={14} color={COPPER}>DIRECT EMITTER  ·  OWN LINKER  ·  REACHABLE CODE ONLY  ·  NO LLVM</text>
    </frame>,
    { at: 44.5, dur: 7.5, name: "Ultra performance" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("06", "ONE MODULE, EVERY PROCESSOR", "Write once. Step on CPU. Launch on GPU.", "The same typed kernel targets CPU, Vulkan, or CUDA without changing languages or build systems.")}
      <frame x={72} y={218} width={730} height={364} layout="none">
        <rect x={0} y={0} width={730} height={364} radius={18} fill="#0d1017" />
        <text x={28} y={28} width={674} height={24} fontFamily={MONO} fontSize={18} color={TEXT}>use e.gpu</text>
        <text x={28} y={70} width={674} height={24} fontFamily={MONO} fontSize={18} color={GREEN}>@gpu(256)</text>
        <text x={28} y={100} width={674} height={24} fontFamily={MONO} fontSize={18} color={TEXT}>{"fn saxpy(a: f32, x: []const f32, y: []f32) {"}</text>
        <text x={28} y={130} width={674} height={24} fontFamily={MONO} fontSize={18} color={TEXT}>    let i = usize(gpu.gid.x)</text>
        <text x={28} y={160} width={674} height={24} fontFamily={MONO} fontSize={18} color={TEXT}>{"    if i < x.len { y[i] = a*x[i] + y[i] }"}</text>
        <text x={28} y={190} width={674} height={24} fontFamily={MONO} fontSize={18} color={TEXT}>{"}"}</text>
        <text x={28} y={250} width={674} height={24} fontFamily={MONO} fontSize={18} color={BLUE}>gpu.launch[saxpy](q, grid, 2.0, dx, dy)</text>
      </frame>
      <frame x={834} y={218} width={374} height={364} layout="none">
        <rect x={0} y={0} width={374} height={104} radius={18} fill={BLUE_DARK} /><text x={24} y={22} width={120} height={42} fontFamily={FONT} fontSize={28} fontWeight={600} color="#ffffff">CPU</text><text x={24} y={68} width={326} height={22} fontFamily={FONT} fontSize={14} color="#dbe6ff">exact deterministic debugging</text>
        <rect x={0} y={130} width={374} height={104} radius={18} fill={PANEL} /><text x={24} y={152} width={160} height={42} fontFamily={FONT} fontSize={28} fontWeight={600} color={BLUE}>Vulkan</text><text x={24} y={198} width={326} height={22} fontFamily={FONT} fontSize={14} color={MUTED}>portable GPU compute</text>
        <rect x={0} y={260} width={374} height={104} radius={18} fill={PANEL} /><text x={24} y={282} width={160} height={42} fontFamily={FONT} fontSize={28} fontWeight={600} color={GREEN}>CUDA</text><text x={24} y={328} width={326} height={22} fontFamily={FONT} fontSize={14} color={MUTED}>native NVIDIA path</text>
      </frame>
    </frame>,
    { at: 52, dur: 6.5, name: "CPU and GPU" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      {heading("07", "BATTERIES INCLUDED", "An ultra-rich standard library.", "One versioned system for algorithms, networking, crypto, codecs, data, ML, GPU compute, and native UI.")}
      <frame x={72} y={218} width={344} height={366} layout="none">
        <rect x={0} y={0} width={344} height={108} radius={18} fill={PANEL} /><text x={24} y={20} width={296} height={48} fontFamily={FONT} fontSize={34} fontWeight={600} color={TEXT}>7,963</text><text x={24} y={72} width={296} height={22} fontFamily={FONT} fontSize={14} color={MUTED}>function signatures</text>
        <rect x={0} y={129} width={344} height={108} radius={18} fill={PANEL} /><text x={24} y={149} width={296} height={48} fontFamily={FONT} fontSize={34} fontWeight={600} color={TEXT}>1,232</text><text x={24} y={201} width={296} height={22} fontFamily={FONT} fontSize={14} color={MUTED}>standard algorithms</text>
        <rect x={0} y={258} width={344} height={108} radius={18} fill={BLUE_DARK} /><text x={24} y={278} width={296} height={48} fontFamily={FONT} fontSize={34} fontWeight={600} color="#ffffff">112</text><text x={24} y={330} width={296} height={22} fontFamily={FONT} fontSize={14} color="#dbe6ff">native UI controls</text>
      </frame>
      <frame x={448} y={218} width={760} height={366} layout="none"><rect x={0} y={0} width={760} height={366} radius={18} fill={PANEL_2} /><media file={forge} x={16} y={16} width={728} height={334} fit="contain" radius={12} /></frame>
    </frame>,
    { at: 58.5, dur: 9.5, name: "Library and native UI" }
  )

  p.compose(
    <frame width={W} height={H} layout="none" background={BG} motion={fade}>
      <rect x={-220} y={-290} width={820} height={820} radius={410} fill={{kind:"radial",stops:[{offset:0,color:"#143d73",opacity:.82},{offset:1,color:BG,opacity:0}]}} />
      <text x={72} y={56} width={1136} height={24} fontFamily={MONO} fontSize={13} fontWeight={700} letterSpacing={1} color={BLUE}>08  /  VERIFIABLE SOFTWARE</text>
      <text x={72} y={104} width={1136} height={76} fontFamily={FONT} fontSize={58} fontWeight={600} color={TEXT}>From prompt to proof.</text>
      <text x={76} y={196} width={1110} height={28} fontFamily={FONT} fontSize={21} color={MUTED}>Every source snapshot, semantic edit, dependency, unsafe boundary,</text>
      <text x={76} y={229} width={1110} height={28} fontFamily={FONT} fontSize={21} color={MUTED}>test, and native artifact is connected by verifiable hashes.</text>
      <frame x={72} y={312} width={1136} height={112} layout="none">
        <rect x={0} y={0} width={190} height={112} radius={18} fill={PANEL} /><text x={0} y={28} width={190} height={28} align="center" fontFamily={FONT} fontSize={18} fontWeight={700} color={TEXT}>PROMPT</text><text x={0} y={68} width={190} height={20} align="center" fontFamily={MONO} fontSize={12} color={BLUE}>intent hash</text>
        <text x={202} y={38} width={44} height={32} align="center" fontFamily={FONT} fontSize={28} color={BLUE}>&gt;</text>
        <rect x={258} y={0} width={190} height={112} radius={18} fill={PANEL} /><text x={258} y={28} width={190} height={28} align="center" fontFamily={FONT} fontSize={18} fontWeight={700} color={TEXT}>SOURCE</text><text x={258} y={68} width={190} height={20} align="center" fontFamily={MONO} fontSize={12} color={BLUE}>snapshot hash</text>
        <text x={460} y={38} width={44} height={32} align="center" fontFamily={FONT} fontSize={28} color={BLUE}>&gt;</text>
        <rect x={516} y={0} width={190} height={112} radius={18} fill={PANEL} /><text x={516} y={28} width={190} height={28} align="center" fontFamily={FONT} fontSize={18} fontWeight={700} color={TEXT}>TESTS</text><text x={516} y={68} width={190} height={20} align="center" fontFamily={MONO} fontSize={12} color={GREEN}>248 passed</text>
        <text x={718} y={38} width={44} height={32} align="center" fontFamily={FONT} fontSize={28} color={BLUE}>&gt;</text>
        <rect x={774} y={0} width={362} height={112} radius={18} fill={BLUE_DARK} /><text x={774} y={26} width={362} height={30} align="center" fontFamily={FONT} fontSize={20} fontWeight={700} color="#ffffff">NATIVE ARTIFACT</text><text x={774} y={68} width={362} height={20} align="center" fontFamily={MONO} fontSize={12} color="#dbe6ff">signed verification receipt</text>
      </frame>
      <frame x={72} y={474} width={760} height={42} layout="none">{pill(0,164,"MIT open source")}{pill(180,210,"100% self-hosted")}{pill(406,238,"Windows · Linux · macOS")}</frame>
      <text x={74} y={552} width={1130} height={26} fontFamily={MONO} fontSize={14} fontWeight={700} color={GREEN}>26 LLM-NATIVE FEATURES  ·  DETERMINISTIC  ·  CONTENT-ADDRESSED</text>
    </frame>,
    { at: 68, dur: 9, name: "From prompt to proof" }
  )

  await p.frame(2, "renders/neper-capabilities-poster.png")
  await p.render("renders/neper-capabilities-clean.mp4", { bitrate: 6000000, concurrency: 4 })
}
